site_name: refCNV Documentation
site_description: 'Documentation for the refCNV resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2024, Michael Baudis and refcnv.org'
repo_name: refcnv-web
repo_url: https://github.com/progenetix/refcnv-web

# vars for common files (shared between sites) #################################

api_site_label: '[refCNV](https://refcnv.org)'
api_web_root: https://refcnv.org
api_dataset_ids: refcnv

################################################################################

nav:
  - Documentation Home: index.md
  - News: news
  - Use Case Examples: use-cases
  - Analysis in R - pgxRpi: pgxRpi
  - refCNV Main Site &#8599;: https://refcnv.org
  - Progenetix Documentation &#8599;: https://docs.progenetix.org
  - Progenetix Data &#8599;: https://progenetix.org
  - cancercelllines.org &#8599;: https://cancercelllines.org
  - Baudisgroup @ UZH &#8599;: https://info.baudisgroup.org

################################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_gh_links:
      user: progenetix
      repo: refcnv-web
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

###############################################################################

theme:
  # name: readthedocs
  name: material
  palette:
    primary: deep purple
  favicon: img/site-logo-topright.png
  logo: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
  custom_dir: extra
      
plugins:
    - search
    - macros
    - mermaid2

extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://genomic.social/@progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/progenetix
extra_css:
  - css/theme_overrides.css
# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    